---
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/wb3-starter/configuration # default
#          search-paths:
#            - '{application}'
security:
  basic:
    enabled: true
  user:
    name: billbensing
    password: billbensing
