---
info:
  component: WB3 - Spring Cloud Configuration Server
server:
  port: 3000
spring:
  application:
    name: wb3-configserver
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        git:
          uri: https://github.com/wb3-spring/configuration
          search-paths:
            - '*' # Search any directory in git repo with '*'; does not limit you to specific directories
#security:
#  basic:
#    enabled: false
#  user:
#    name: billbensing
#    password: billbensing